
service: pplns-core
useDotenv: true
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
custom:
  localDevStaticFolder: ./
  webpack:
    packager: 'yarn'
    includeModules: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage}
  region: eu-central-1
  memorySize: 128
  profile: default
  lambdaHashingVersion: '20201221'
functions:
  app:
    handler: lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY
